### ISSUE TITLE
【游戏中心签到】: 错误，原因为: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jarryyen** [srcrs/unicom-task#27]
[2021-08-18 10:54:33,154]:INFO:【登录】: 0251
[2021-08-18 10:54:34,931]:INFO:【通信积分】: 238
[2021-08-18 10:54:34,932]:INFO:【奖励积分】: 177
[2021-08-18 10:54:34,932]:INFO:【定向积分】: 9800
[2021-08-18 10:54:34,932]:INFO:【优惠券】: 0
[2021-08-18 10:54:39,255]:INFO:【即将过期流量包】: 暂无
[2021-08-18 10:54:40,781]:INFO:【沃之树-领流量新】: 4M流量 x1
[2021-08-18 10:54:43,492]:INFO:【沃之树-领流量】: 4M流量 x3
[2021-08-18 10:54:45,926]:INFO:【沃之树-领流量】: 4M流量 x5
[2021-08-18 10:54:48,420]:INFO:【沃之树-领流量】: 4M流量 x7
[2021-08-18 10:54:50,128]:INFO:【沃之树-浇水】: 获得0培养值
[2021-08-18 10:54:56,097]:INFO:【每日签到】: 您今天已经签到啦
Traceback (most recent call last):
  File "/root/unicom-task/task/game_signin.py", line 34, in run
    res1 = gameCenter.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[2021-08-18 10:55:35,309]:ERROR:【游戏中心签到】: 错误，原因为: Expecting value: line 1 column 1 (char 0)

望修复,谢

**Comment by jarryyen** [comment]
res1 = gameCenter.json()

这个 gameCenter 有时候获取的信息是 <Response [200]>

可能需要一个判断

**Comment by YvoIovY** [comment]
求云函数部署具体教程，两种方法部署后运行都报错。
