### ISSUE TITLE
求云函数吧7部署具体教程，两种方法部署后运行都报错。

### ISSUE THREAD

**Issue by YvoIovY** [srcrs/unicom-task#31]

**Comment by srcrs** [comment]
给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看

**Comment by Mutx163** [comment]
START RequestId:d29a6d03-cd8b-4a56-9b94-1df0f267c6c7
Traceback (most recent call last):
    users = json.load(fp)
  File "/var/user/index.py", line 245, in readJson
  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 299, in load
  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 339, in decode
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/var/lang/python3/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    obj, end = self.scan_once(s, idx)
  File "/var/lang/python3/lib/python3.6/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Invalid control character at: line 5 column 179 (char 251)

账号信息获取失败错误，原因为: Invalid control character at: line 5 column 179 (char 251)
[2021-08-20 17:53:56,152]:ERROR:账号信息获取失败错误，原因为: Invalid control character at: line 5 column 179 (char 251)
1.请检查是否在Secrets添加了账号信息，以及添加的位置是否正确。
[2021-08-20 17:53:56,153]:ERROR:1.请检查是否在Secrets添加了账号信息，以及添加的位置是否正确。
2.填写之前，是否在网站验证过Json格式的正确性。
[2021-08-20 17:53:56,153]:ERROR:2.填写之前，是否在网站验证过Json格式的正确性。
ERROR RequestId:d29a6d03-cd8b-4a56-9b94-1df0f267c6c7 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 426, in main_handler\n    for user in users:\nTypeError: 'NoneType' object is not iterable","statusCode":430}
END RequestId:d29a6d03-cd8b-4a56-9b94-1df0f267c6c7
Report RequestId:d29a6d03-cd8b-4a56-9b94-1df0f267c6c7 Duration:2ms Memory:128MB MemUsage:31.242188MB

**Comment by Mutx163** [comment]
上面发的是腾讯云函数的报错

**Comment by YvoIovY** [comment]
压缩包部署后报错和上面一样。

**Comment by YvoIovY** [comment]
下面的是yml方式本地部署后，运行报错内容。

**Comment by YvoIovY** [comment]
总览
云产品

搜索产品、文档...

小程序
19
集团账号
备案
工具
支持
费用
OO
icon
icon
icon
icon
icon
icon
icon
unicom-Task正常
函数服务帮助文档
函数管理
触发管理
监控信息
日志查询
并发配额
部署日志
函数管理
版本：$LATEST
操作
函数配置函数代码层管理监控信息日志查询
68
    main_handler("","")
import requests,json,time,re,login,logging,traceback,os,random,notify,datetime,util
from lxml.html import fromstring
import pytz,importlib

#用户登录全局变量
client = None

#读取用户配置信息
#错误原因有两种：格式错误、未读取到错误
def readJson():

{  "key1": "test value 1",  "key2": "test value 2"}

{
  "key1": "test value 1",
  "key2": "test value 2"
}
调用日志高级检索
全部日志
近15分钟

2021-08-21 08:35:05 ~ 2021-08-21 08:50:05
刷新

请输入requestID

2021-08-21 08:48:56	调用失败
请求Id：ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4
时间：2021-08-21 08:48:56运行时间:0ms运行内存:0.00MB
日志:

START RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4
ERROR RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 1, in \u003cmodule\u003e\n    import requests,json,time,re,login,logging,traceback,os,random,notify,datetime,util\n  File \"/var/user/login.py\", line 6, in \u003cmodule\u003e\n    import base64,rsa,time,requests,logging,traceback,os\nModuleNotFoundError: No module named 'rsa'","statusCode":443}
END RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4
Report RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by YvoIovY** [comment]
> 给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看

麻烦大佬看一下

**Comment by YvoIovY** [comment]
日志:

START RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4
ERROR RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 1, in \u003cmodule\u003e\n    import requests,json,time,re,login,logging,traceback,os,random,notify,datetime,util\n  File \"/var/user/login.py\", line 6, in \u003cmodule\u003e\n    import base64,rsa,time,requests,logging,traceback,os\nModuleNotFoundError: No module named 'rsa'","statusCode":443}
END RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4
Report RequestId:ef15cbd7-36ba-4a6f-b0ab-f5d8c25652d4 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by Saxon-Sun** [comment]
> 给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看

麻烦构建的时候把cron启动一下  不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动

**Comment by Dellear** [comment]
> 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动

可以使用这个镜像 dellear/unicom-task

**Comment by Saxon-Sun** [comment]
> > 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动
> 
> 可以使用这个镜像 dellear/unicom-task

我自己重新打包镜像了 也能用啦

**Comment by Mutx163** [comment]
> > 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动
> 
> 可以使用这个镜像 dellear/unicom-task

大佬，这个镜像可以在腾讯云上搭建吗

**Comment by YvoIovY** [comment]
> > 给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看
> 
> 麻烦构建的时候把cron启动一下 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动

你不会自己开issue么？

**Comment by Saxon-Sun** [comment]
> > > 给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看
> > 
> > 
> > 麻烦构建的时候把cron启动一下 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动
> 
> 你不会自己开issue么？

开一个issue和回复有区别吗  别搞笑

**Comment by YvoIovY** [comment]
> > > > 给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看
> > > 
> > > 
> > > 麻烦构建的时候把cron启动一下 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动
> > 
> > 
> > 你不会自己开issue么？
> 
> 开一个issue和回复有区别吗 别搞笑

也对，乞丐到哪都能要饭。

**Comment by Saxon-Sun** [comment]
> > > > > 给一下，报错信息看看，云函数还没有更新，估计会有问题，docker报错信息我看看
> > > > 
> > > > 
> > > > 麻烦构建的时候把cron启动一下 不然重启容器cron又不启动了 我现在的解决方案是用Dockerfile把images重新打包加上cron启动
> > > 
> > > 
> > > 你不会自己开issue么？
> > 
> > 
> > 开一个issue和回复有区别吗 别搞笑
> 
> 也对，乞丐到哪都能要饭。

笑死我了 我看每个issue你都要要饭  你对这个项目贡献什么了 ？？？
